backend:
  name: github
  repo: weloveludgeriplatz/weloveludgeriplatz.github.io
  branch: dev

  base_url: https://decap-auth.weloveludgeriplatz.workers.dev
  auth_endpoint: auth

local_backend: true

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"

    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/base.njk",
        }

      - { label: "Title", name: "title", widget: "string" }

      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Paragraph"
            name: "paragraph"
            widget: "object"
            fields:
              - {
                  label: "Style",
                  name: "style",
                  widget: "select",
                  options:
                    [
                      { label: "orange", value: "orange" },
                      { label: "violet", value: "violet" },
                      { label: "white", value: "white" },
                      { label: "white + orange", value: "white_orange" },
                      { label: "white + violet", value: "white_violet" },
                    ],
                }
              - { label: "Content", name: "content", widget: "markdown" }

          - label: "Button"
            name: "button"
            widget: "object"
            fields:
              - {
                  label: "Style",
                  name: "style",
                  widget: "select",
                  options: ["orange", "violet"],
                  default: "orange",
                }
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Link", name: "url", widget: "string" }

          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - {
                  label: "Style",
                  name: "style",
                  widget: "select",
                  options: ["orange", "violet"],
                  default: "orange",
                }
              - { label: "drive-image", name: "src", widget: "drive-image" }
              - { label: "Alt Text", name: "alt", widget: "string" }

          - label: "Image + Text"
            name: "image-text"
            widget: "object"
            fields:
              - {
                  label: "Style",
                  name: "style",
                  widget: "select",
                  options: ["orange", "violet"],
                  default: "orange",
                }
              - {
                  label: "Side",
                  name: "side",
                  widget: "select",
                  options: ["left", "right"],
                  default: "left",
                }
              - { label: "Image", name: "src", widget: "drive-image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
